# Generated by Django 5.1.6 on 2025-03-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
