# Generated by Django 5.1.6 on 2025-03-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0004_delete_userstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=50)),
                ('contest_data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('username', 'platform')},
            },
        ),
    ]
