# Generated by Django 4.2 on 2026-05-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContestHistory',
        ),
    ]
